# Generated by Django 5.1 on 2024-08-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_alter_course_credit_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='courses',
            field=models.ManyToManyField(related_name='semesters', to='exam.course'),
        ),
    ]
