# Generated by Django 5.1 on 2024-08-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_remove_student_enrollment_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='courses',
            field=models.ManyToManyField(to='exam.course'),
        ),
    ]
