# Generated by Django 5.1 on 2024-08-16 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_student_enrollment_year_student_faculty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='enrollment_year',
        ),
        migrations.RemoveField(
            model_name='student',
            name='faculty',
        ),
    ]
