# Generated by Django 5.1 on 2024-08-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_student_enrollment_year_student_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='credit_hours',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
