# Generated by Django 5.1 on 2024-08-19 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0011_alter_course_credit_hours'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='enrollment_year',
            new_name='batch',
        ),
    ]
