# Generated by Django 5.1 on 2024-08-20 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0013_batch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batch',
            old_name='semester',
            new_name='semesters',
        ),
        migrations.RenameField(
            model_name='batch',
            old_name='student',
            new_name='students',
        ),
    ]
