# Generated by Django 5.1 on 2024-08-20 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0015_examresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examresult',
            name='grade_point',
        ),
        migrations.AlterField(
            model_name='examresult',
            name='remarks',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
