# Generated by Django 5.1 on 2024-08-20 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0016_remove_examresult_grade_point_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='grade',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
