# Generated by Django 5.1 on 2024-08-20 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0017_examresult_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresult',
            name='grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4),
        ),
    ]
