# Generated by Django 5.1 on 2024-08-20 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0018_alter_examresult_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examresult',
            name='grade',
        ),
    ]
