# Generated by Django 5.1 on 2024-08-21 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0019_remove_examresult_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='grade_points',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
