# Generated by Django 5.1 on 2024-08-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0020_examresult_grade_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='course',
        ),
        migrations.AddField(
            model_name='batch',
            name='course',
            field=models.ManyToManyField(to='exam.course'),
        ),
    ]
