# Generated by Django 5.1 on 2024-08-21 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0021_remove_batch_course_batch_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examresult',
            old_name='remarks',
            new_name='description',
        ),
    ]
