# Generated by Django 5.1 on 2024-08-21 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0022_rename_remarks_examresult_description'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examresult',
            unique_together={('student', 'course', 'semester')},
        ),
    ]
