# Generated by Django 5.1 on 2024-08-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0023_alter_examresult_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examresult',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='student',
        ),
        migrations.AddField(
            model_name='examresult',
            name='student',
            field=models.ManyToManyField(to='exam.student'),
        ),
    ]
