# Generated by Django 5.1 on 2024-08-21 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0024_alter_examresult_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examresult',
            name='student',
        ),
        migrations.AddField(
            model_name='examresult',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exam.student'),
            preserve_default=False,
        ),
    ]
