# Generated by Django 5.1 on 2024-08-21 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0026_alter_examresult_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.student'),
        ),
    ]
