# Generated by Django 5.1 on 2024-08-21 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0029_alter_faculty_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='course',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='semesters',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='students',
        ),
        migrations.AddField(
            model_name='batch',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exam.department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batch',
            name='faculty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exam.faculty'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='batch',
            name='year',
            field=models.CharField(max_length=300),
        ),
    ]
