# Generated by Django 5.1 on 2024-08-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0030_remove_batch_course_remove_batch_semesters_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examresult',
            name='description',
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='grade_points',
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='score',
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='semester',
        ),
        migrations.AddField(
            model_name='examresult',
            name='assessment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='examresult',
            name='final_exam',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='examresult',
            name='mid_exam',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
