# Generated by Django 5.1 on 2024-08-21 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0031_remove_examresult_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examresult',
            name='final_exam',
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='mid_exam',
        ),
        migrations.AddField(
            model_name='examresult',
            name='final',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examresult',
            name='mid_term',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examresult',
            name='remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='examresult',
            name='semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exam.semester'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examresult',
            name='total_score',
            field=models.DecimalField(decimal_places=2, default=1, editable=False, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='examresult',
            name='assessment',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
