# Generated by Django 5.1 on 2024-08-21 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0032_remove_examresult_final_exam_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examresult',
            old_name='assessment',
            new_name='score',
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='final',
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='mid_term',
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='total_score',
        ),
        migrations.AddField(
            model_name='examresult',
            name='grade_point',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='remarks',
            field=models.CharField(blank=True, default=1, max_length=30),
            preserve_default=False,
        ),
    ]
