# Generated by Django 5.1 on 2024-08-21 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0033_rename_assessment_examresult_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='faculty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exam.faculty'),
            preserve_default=False,
        ),
    ]
