# Generated by Django 5.1 on 2024-08-21 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0034_semester_faculty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examresult',
            old_name='score',
            new_name='assessment',
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='grade_point',
        ),
        migrations.AddField(
            model_name='examresult',
            name='final_exam',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examresult',
            name='mid_exam',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='examresult',
            name='remarks',
            field=models.TextField(blank=True),
        ),
    ]
