# Generated by Django 5.1 on 2024-08-21 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0035_rename_score_examresult_assessment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examresult',
            old_name='assessment',
            new_name='score',
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='final_exam',
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='mid_exam',
        ),
        migrations.AddField(
            model_name='examresult',
            name='grade_point',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='remarks',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
