# Generated by Django 5.1 on 2024-08-21 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0036_rename_assessment_examresult_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.batch'),
        ),
    ]
