# Generated by Django 5.1 on 2024-08-21 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0037_alter_student_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examresult',
            name='grade_point',
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='remarks',
        ),
        migrations.AddField(
            model_name='examresult',
            name='credit_points',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examresult',
            name='grade',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='score',
            field=models.FloatField(),
        ),
    ]
