# Generated by Django 5.1 on 2024-08-24 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0040_alter_course_code_alter_faculty_faculty_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examresult',
            old_name='score',
            new_name='assissments',
        ),
        migrations.AddField(
            model_name='examresult',
            name='final_exam',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examresult',
            name='mid_exam',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examresult',
            name='total_score',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
