# Generated by Django 5.1 on 2024-08-24 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0041_rename_score_examresult_assissments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examresult',
            name='total_score',
        ),
        migrations.AddField(
            model_name='examresult',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='final_exam',
            field=models.FloatField(blank=True),
        ),
    ]
